#!/opt/perl/bin/perl
use strict;
use AnyEvent;
use BS::HTTPD;
use BS::HTTPD::Appgets;

my $cvar = AnyEvent->condvar;

my $httpd = BS::HTTPD->new (port => 9090);

my $t;

$httpd->reg_cb (
   _ => sub {
      my ($httpd, $req) = @_;
      set_request ($req);

      o capture {
         o "<html><body><h1>Hello World!</h1>";
         o "<a href=\"/test\">another test page</a>";
         o "</body></html>";
      };

      $req->respond;
   },
   _test => sub {
      my ($httpd, $req) = @_;

      $t = AnyEvent->timer (after => 2, cb => sub {
         my $o = capture {
            o "CPU info:\n\n";
            o `cat /proc/cpuinfo`;
         };
         $req->respond ([200, "ok", { 'Content-Type' => 'text/plain' }, $o]);
      });

      'delay'
   },
);

$cvar->wait;
