#!/opt/perl/bin/perl
use AnyEvent;
use BS::HTTPD;

my $cvar = AnyEvent->condvar;

my $httpd = BS::HTTPD->new (port => 9090);

my $timer;
$httpd->reg_cb (
   _ => sub {
      my ($httpd, $url, $headers) = @_;

      $httpd->o ("<html><body><h1>Testing return types...</h1>");
      $httpd->o ("<img src=\"/image/bshttp.png\" />");
      $httpd->o ("</body></html>");

      () # !
   },
   '_image_bshttp.png' => sub {
      my $rcb = $_[0]->response_handle;

      $timer = AnyEvent->timer (after => 3, cb => sub {
         open IMG, 'bshttp.png' or do { $rcb->(); return };

         $rcb->({ content => [ 'image/png', do { local $/; <IMG> } ] });
      });

      'delay'
   },
);

$cvar->wait;
